services:
  backend:
    build: ./backend
    volumes:
      - sockets:/run
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - sockets:/run:rw
    restart: unless-stopped

volumes:
  sockets:
    driver: local
